# Generated by Django 3.0.5 on 2020-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('hospital', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('emotion', models.IntegerField()),
                ('WBC', models.IntegerField()),
                ('RBC', models.IntegerField()),
                ('PT', models.IntegerField()),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
