# Generated by Django 2.2.5 on 2020-05-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20200430_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='hospital',
        ),
    ]
