# Generated by Django 2.2.5 on 2020-05-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20200511_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='neutrophil',
            field=models.IntegerField(default=0),
        ),
    ]
