# Generated by Django 2.2.5 on 2020-05-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_diary_neutrophil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='title',
        ),
    ]
