# Generated by Django 2.2.5 on 2020-05-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_remove_diary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.CharField(default='no text', max_length=20),
        ),
    ]
