# Generated by Django 2.2.5 on 2020-05-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_diary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='PT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diary',
            name='RBC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diary',
            name='WBC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(default='no text'),
        ),
    ]
