# Generated by Django 2.2.5 on 2020-06-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20200609_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='captiion',
            new_name='caption',
        ),
    ]
