# Generated by Django 3.0.5 on 2020-04-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='zone_category',
        ),
        migrations.AddField(
            model_name='hospital',
            name='zone',
            field=models.IntegerField(choices=[(1, '서울'), (2, '경기,인천'), (3, '강원'), (4, '충청'), (5, '경상'), (6, '제주')], default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='site_url',
            field=models.URLField(),
        ),
    ]
